package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"os/signal"
	"strings"
	"syscall"

	"agentbox/internal/config"
	"agentbox/internal/credstore"
	"agentbox/internal/paths"
)

// cmdAddSecret stores a credential encrypted at rest. The value is read from
// a terminal without echo (or from stdin when piped) and handed to
// systemd-creds over a pipe, so it is never written to disk in plaintext and
// never appears in argv, shell history, or the terminal scrollback.
func cmdAddSecret(args []string) int {
	fs := flag.NewFlagSet("add-secret", flag.ContinueOnError)
	dir := fs.String("secrets-dir", paths.Secrets, "directory holding encrypted credentials")
	credsBin := fs.String("systemd-creds", "systemd-creds", "systemd-creds binary")
	rest, ok := parseArgs(fs, args)
	if !ok {
		return 2
	}
	if len(rest) != 1 {
		fmt.Fprintln(os.Stderr, "usage: agentbox add-secret <name>   (value on stdin, or prompted)")
		return 2
	}
	name := rest[0]
	// Stricter than credstore.ValidName, which must also accept the generated
	// `<name>.basic` companions: a source secret has to be referenceable from
	// routes.json, whose {secret:NAME} template forbids dots.
	if !config.ValidSecretName(name) {
		return fail(fmt.Errorf("invalid secret name %q (lowercase letters, digits and dashes; must be usable in a routes.json {secret:...} template)", name))
	}
	if strings.HasSuffix(name, ".basic") {
		return fail(fmt.Errorf("%q is generated by agentbox setup; add the source secret instead", name))
	}
	if os.Geteuid() != 0 {
		return fail(fmt.Errorf("must run as root (sudo agentbox add-secret %s)", name))
	}

	store := credstore.Store{Dir: *dir, Bin: *credsBin}
	if err := store.Available(); err != nil {
		return fail(err)
	}

	value, err := readSecret(name)
	if err != nil {
		return fail(err)
	}
	if strings.TrimSpace(string(value)) != string(value) {
		fmt.Fprintln(os.Stderr, "note: trimming surrounding whitespace from the value")
	}
	// Trimming, emptiness and charset are enforced by credstore.Put, which is
	// also what the plaintext migration goes through.

	replacing := store.Has(name)
	if err := store.Put(name, value); err != nil {
		return fail(err)
	}
	verb := "stored"
	if replacing {
		verb = "replaced"
	}
	fmt.Printf("%s %s (encrypted at rest, %s)\n", verb, name, store.Path(name))
	fmt.Println("next: sudo agentbox setup   # loads it into caddy and re-enables its routes")
	return 0
}

// maxSecretBytes bounds a piped value. systemd caps accumulated credentials
// at 1 MB per unit; anything near that is a mistake, not a token.
const maxSecretBytes = 64 << 10

// readSecret takes the value from stdin when piped, and otherwise prompts on
// the terminal with echo disabled.
func readSecret(name string) ([]byte, error) {
	fi, err := os.Stdin.Stat()
	if err != nil {
		return nil, err
	}
	if fi.Mode()&os.ModeCharDevice == 0 {
		value, err := io.ReadAll(io.LimitReader(os.Stdin, maxSecretBytes+1))
		if err != nil {
			return nil, err
		}
		if len(value) > maxSecretBytes {
			return nil, fmt.Errorf("value exceeds %d bytes; that is not a credential", maxSecretBytes)
		}
		return value, nil
	}
	fmt.Fprintf(os.Stderr, "value for %s (input hidden): ", name)
	value, err := readNoEcho(os.Stdin)
	fmt.Fprintln(os.Stderr)
	return value, err
}

// readNoEcho reads one line with terminal echo turned off, restoring the
// previous terminal state afterwards — including on SIGINT, which would
// otherwise leave the operator's shell silently un-echoing.
func readNoEcho(f *os.File) ([]byte, error) {
	fd := int(f.Fd())
	var old syscall.Termios
	if err := ioctlTermios(fd, tcGets, &old); err != nil {
		// Not a terminal at all; a plain read echoes nothing extra.
		return readLine(f)
	}
	noEcho := old
	noEcho.Lflag &^= syscall.ECHO
	if err := ioctlTermios(fd, tcSets, &noEcho); err != nil {
		// This IS a terminal and echo is still on. Reading here would print
		// the secret to the screen and into scrollback, which is exactly
		// what this command promises not to do.
		return nil, fmt.Errorf("cannot disable terminal echo (%w); pipe the value in instead", err)
	}
	restore := func() { ioctlTermios(fd, tcSets, &old) }
	defer restore()
	sigs := make(chan os.Signal, 1)
	// SIGTSTP matters as much as SIGINT here: Ctrl-Z at a password prompt
	// would otherwise leave the operator's shell echo-less while stopped.
	signal.Notify(sigs, os.Interrupt, syscall.SIGTERM, syscall.SIGQUIT, syscall.SIGTSTP, syscall.SIGHUP)
	defer signal.Stop(sigs)
	done := make(chan struct{})
	defer close(done)
	go func() {
		select {
		case s := <-sigs:
			restore()
			fmt.Fprintln(os.Stderr)
			// Reset to the default disposition and re-raise, so the shell
			// sees the signal it expects (stop for TSTP, death for the rest).
			signal.Stop(sigs)
			signal.Reset(s.(syscall.Signal))
			if p, err := os.FindProcess(os.Getpid()); err == nil {
				_ = p.Signal(s)
			}
		case <-done:
		}
	}()
	return readLine(f)
}

func readLine(f *os.File) ([]byte, error) {
	var out []byte
	buf := make([]byte, 1)
	for {
		n, err := f.Read(buf)
		if n > 0 {
			if buf[0] == '\n' {
				break
			}
			out = append(out, buf[0])
		}
		if err != nil {
			if err == io.EOF {
				break
			}
			return nil, err
		}
	}
	return out, nil
}
