package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"strings"
	"syscall"

	"agentbox/internal/credstore"
	"agentbox/internal/paths"
)

// cmdAddSecret stores a credential encrypted at rest. The value is read from
// a terminal without echo (or from stdin when piped) and handed to
// systemd-creds over a pipe, so it is never written to disk in plaintext and
// never appears in argv, shell history, or the terminal scrollback.
func cmdAddSecret(args []string) int {
	fs := flag.NewFlagSet("add-secret", flag.ContinueOnError)
	dir := fs.String("secrets-dir", paths.Secrets, "directory holding encrypted credentials")
	credsBin := fs.String("systemd-creds", "systemd-creds", "systemd-creds binary")
	rest, ok := parseArgs(fs, args)
	if !ok {
		return 2
	}
	if len(rest) != 1 {
		fmt.Fprintln(os.Stderr, "usage: agentbox add-secret <name>   (value on stdin, or prompted)")
		return 2
	}
	name := rest[0]
	if !credstore.ValidName(name) {
		return fail(fmt.Errorf("invalid secret name %q (lowercase letters, digits, dot and dash)", name))
	}
	if strings.HasSuffix(name, ".basic") {
		return fail(fmt.Errorf("%q is generated by `agentbox setup`; add the source secret instead", name))
	}
	if os.Geteuid() != 0 {
		return fail(fmt.Errorf("must run as root (sudo agentbox add-secret %s)", name))
	}

	store := credstore.Store{Dir: *dir, Bin: *credsBin}
	if err := store.Available(); err != nil {
		return fail(err)
	}

	value, err := readSecret(name)
	if err != nil {
		return fail(err)
	}
	// A trailing newline from a paste would otherwise ride along into the
	// injected header; Caddy strips exactly one, so a blank line would
	// produce a malformed value.
	value = []byte(strings.TrimRight(string(value), " \t\r\n"))
	if len(value) == 0 {
		return fail(fmt.Errorf("empty value; nothing stored for %q", name))
	}

	replacing := store.Has(name)
	if err := store.Put(name, value); err != nil {
		return fail(err)
	}
	verb := "stored"
	if replacing {
		verb = "replaced"
	}
	fmt.Printf("%s %s (encrypted at rest, %s)\n", verb, name, store.Path(name))
	fmt.Println("next: sudo agentbox setup   # loads it into caddy and re-enables its routes")
	return 0
}

// readSecret takes the value from stdin when piped, and otherwise prompts on
// the terminal with echo disabled.
func readSecret(name string) ([]byte, error) {
	fi, err := os.Stdin.Stat()
	if err != nil {
		return nil, err
	}
	if fi.Mode()&os.ModeCharDevice == 0 {
		return io.ReadAll(os.Stdin) // piped or redirected
	}
	fmt.Fprintf(os.Stderr, "value for %s (input hidden): ", name)
	value, err := readNoEcho(os.Stdin)
	fmt.Fprintln(os.Stderr)
	return value, err
}

// readNoEcho reads one line with terminal echo turned off, restoring the
// previous terminal state afterwards.
func readNoEcho(f *os.File) ([]byte, error) {
	fd := int(f.Fd())
	var old syscall.Termios
	if err := ioctlTermios(fd, tcGets, &old); err != nil {
		// Not a terminal we can control; fall back to a plain read rather
		// than refusing to work.
		return readLine(f)
	}
	noEcho := old
	noEcho.Lflag &^= syscall.ECHO
	if err := ioctlTermios(fd, tcSets, &noEcho); err != nil {
		return readLine(f)
	}
	defer ioctlTermios(fd, tcSets, &old)
	return readLine(f)
}

func readLine(f *os.File) ([]byte, error) {
	var out []byte
	buf := make([]byte, 1)
	for {
		n, err := f.Read(buf)
		if n > 0 {
			if buf[0] == '\n' {
				break
			}
			out = append(out, buf[0])
		}
		if err != nil {
			if err == io.EOF {
				break
			}
			return nil, err
		}
	}
	return out, nil
}
